"""v0.11 Phase C -- Prometheus /metrics endpoint.

Exposes the in-memory provider observability metrics in Prometheus
text format.  **Disabled by default**: when
``Settings.prometheus_enabled`` is ``False`` the endpoint returns
``404 Not Found`` so probes / scrapers cannot tell whether the
process is healthy from a metrics point of view.

Read-only: ``POST`` / ``PUT`` / ``DELETE`` on the same path return
``405 Method Not Allowed`` (FastAPI's default behaviour, kept by
binding only ``GET``).

The response payload is generated by
:func:`app.monitoring.prometheus.render_metrics` and contains only
counter / gauge / histogram lines with provider name + error_kind
labels -- no API key, no URL, no message text appears in any sample.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Response, status

from app.config.settings import Settings, get_settings
from app.monitoring.prometheus import render_metrics

router = APIRouter(tags=["metrics"])


@router.get("/metrics", include_in_schema=False)
def get_metrics_endpoint(
    settings: Settings = Depends(get_settings),
) -> Response:
    """Serve Prometheus text-format metrics, or 404 when disabled.

    The route is intentionally not registered with a schema entry --
    Prometheus exposition is operational tooling, not a public API.
    """
    if not settings.prometheus_enabled:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="not found"
        )
    payload, content_type = render_metrics()
    return Response(content=payload, media_type=content_type)
