"""baseline v0_7 -- 27 tables snapshot at v0.7-final

Revision ID: 0001_baseline_v0_7
Revises:
Create Date: 2026-05-06

This is the Alembic baseline for the Stock AI Platform. It re-creates the 27
tables that existed at v0.7-final (HEAD 1f5b01f) and is intended to be the
single source of truth for any newly bootstrapped database.

Operational guidance:
  * New databases: ``alembic upgrade head`` creates all 27 tables. After that,
    every later revision (Phase B/C/...) layers on top.
  * Existing operational databases (already running with the 27 tables created
    via ``Base.metadata.create_all``): take a backup, then ``alembic stamp
    0001_baseline_v0_7`` to mark the baseline as applied without re-running the
    DDL, then ``alembic upgrade head`` to apply later revisions only.
  * Downgrade is provided for development / verification only -- in production
    the recommended rollback path is to restore the pre-upgrade backup.

Generated via ``alembic revision --autogenerate`` against an empty SQLite
database with ``app.db.models.Base.metadata`` as the target. The migration
test (tests/integration/test_alembic_migration.py) re-runs this revision
against a fresh temporary SQLite and asserts that ``compare_metadata`` reports
zero diffs against the live ORM metadata -- so any future ORM change without a
matching revision will fail CI.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline_v0_7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('broker_name', sa.String(length=64), nullable=False),
    sa.Column('broker_country', sa.String(length=32), nullable=True),
    sa.Column('analyst_name', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.String(length=32), nullable=True),
    sa.Column('normalized_rating', sa.String(length=16), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('previous_target_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('current_price_at_report', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('positive_points', sa.Text(), nullable=True),
    sa.Column('risk_points', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_file_path', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('source_reliability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('duplicate_group_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_name', 'published_at', 'title', name='uq_analyst_reports_broker_pub_title')
    )
    with op.batch_alter_table('analyst_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_reports_duplicate_group_key'), ['duplicate_group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_reports_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_reports_symbol'), ['symbol'], unique=False)

    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('buy_count', sa.Integer(), nullable=False),
    sa.Column('avoid_count', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('win_rate_1d', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('win_rate_3d', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('win_rate_5d', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('win_rate_20d', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('avg_return_1d', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('avg_return_3d', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('avg_return_5d', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('avg_return_20d', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_run_date'), ['run_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_runs_strategy_name'), ['strategy_name'], unique=False)

    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('trading_value', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_daily_prices_symbol_date')
    )
    with op.batch_alter_table('daily_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_prices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_prices_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_daily_prices_symbol_date', ['symbol', 'date'], unique=False)

    op.create_table('data_snapshots',
    sa.Column('snapshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_type', sa.String(length=64), nullable=False),
    sa.Column('price_data_json', sa.JSON(), nullable=True),
    sa.Column('indicator_data_json', sa.JSON(), nullable=True),
    sa.Column('news_data_json', sa.JSON(), nullable=True),
    sa.Column('market_context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    with op.batch_alter_table('data_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_snapshots_snapshot_time'), ['snapshot_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_snapshots_snapshot_type'), ['snapshot_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_snapshots_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_data_snapshots_symbol_type_time', ['symbol', 'snapshot_type', 'snapshot_time'], unique=False)

    op.create_table('earnings_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('revenue_actual', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('revenue_consensus', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('operating_income_actual', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('operating_income_consensus', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('net_income_actual', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('net_income_consensus', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('eps_actual', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('eps_consensus', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('surprise_type', sa.String(length=16), nullable=True),
    sa.Column('surprise_pct', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'event_date', 'fiscal_year', 'fiscal_quarter', 'event_type', name='uq_earnings_events_symbol_event')
    )
    with op.batch_alter_table('earnings_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_earnings_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_earnings_events_surprise_type'), ['surprise_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_earnings_events_symbol'), ['symbol'], unique=False)

    op.create_table('fundamental_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('bps', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('per', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pbr', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('debt_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('operating_income_growth_yoy', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', 'fiscal_year', 'fiscal_quarter', name='uq_fundamental_snapshots_symbol_period')
    )
    with op.batch_alter_table('fundamental_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fundamental_snapshots_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_fundamental_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fundamental_snapshots_symbol'), ['symbol'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('avg_buy_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=True),
    sa.Column('strategy_type', sa.String(length=32), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_holdings_symbol_active', ['symbol', 'is_active'], unique=False)

    op.create_table('job_runs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_name'), ['job_name'], unique=False)
        batch_op.create_index('ix_job_runs_name_status', ['job_name', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_status'), ['status'], unique=False)

    op.create_table('market_cap_rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rank_date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('listed_shares', sa.BigInteger(), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('trading_value', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('is_analysis_target', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rank_date', 'market', 'rank', name='uq_market_cap_rank_date_market_rank'),
    sa.UniqueConstraint('rank_date', 'market', 'symbol', name='uq_market_cap_rank_date_market_symbol')
    )
    with op.batch_alter_table('market_cap_rankings', schema=None) as batch_op:
        batch_op.create_index('ix_market_cap_rankings_date_market', ['rank_date', 'market'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_cap_rankings_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_cap_rankings_rank_date'), ['rank_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_cap_rankings_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_market_cap_rankings_symbol_date', ['symbol', 'rank_date'], unique=False)

    op.create_table('market_regimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('regime', sa.String(length=64), nullable=False),
    sa.Column('market_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'market', name='uq_market_regimes_date_market')
    )
    with op.batch_alter_table('market_regimes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_regimes_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_regimes_market'), ['market'], unique=False)
        batch_op.create_index('ix_market_regimes_market_date', ['market', 'date'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('related_symbols', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(length=32), nullable=True),
    sa.Column('importance', sa.String(length=32), nullable=True),
    sa.Column('theme', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'url', name='uq_news_items_source_url')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index('ix_news_items_published_source', ['published_at', 'source'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_theme'), ['theme'], unique=False)

    op.create_table('recommendation_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('telegram_sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.create_index('ix_recommendation_runs_date_status', ['run_date', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_runs_run_date'), ['run_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_runs_status'), ['status'], unique=False)

    op.create_table('report_consensus_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('avg_target_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('min_target_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('max_target_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('strong_buy_count', sa.Integer(), nullable=False),
    sa.Column('buy_count', sa.Integer(), nullable=False),
    sa.Column('hold_count', sa.Integer(), nullable=False),
    sa.Column('sell_count', sa.Integer(), nullable=False),
    sa.Column('strong_sell_count', sa.Integer(), nullable=False),
    sa.Column('latest_published_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', 'window_days', name='uq_report_consensus_symbol_date_window')
    )
    with op.batch_alter_table('report_consensus_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_consensus_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_consensus_snapshots_symbol'), ['symbol'], unique=False)

    op.create_table('stock_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('ma5', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ma20', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ma60', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ma120', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('rsi14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume_ratio_20d', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('breakout_20d', sa.Boolean(), nullable=True),
    sa.Column('breakout_60d', sa.Boolean(), nullable=True),
    sa.Column('ma_alignment', sa.String(length=32), nullable=True),
    sa.Column('technical_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('atr14', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('candle_patterns', sa.JSON(), nullable=True),
    sa.Column('volatility_band', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_stock_indicators_symbol_date')
    )
    with op.batch_alter_table('stock_indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_indicators_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_indicators_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_stock_indicators_symbol_date', ['symbol', 'date'], unique=False)

    op.create_table('stock_universes',
    sa.Column('universe_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('universe_id')
    )
    with op.batch_alter_table('stock_universes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_universes_name'), ['name'], unique=True)

    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('theme_tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_symbol'), ['symbol'], unique=True)

    op.create_table('decision_logs',
    sa.Column('decision_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_type', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('input_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('rule_result_json', sa.JSON(), nullable=True),
    sa.Column('ai_result_json', sa.JSON(), nullable=True),
    sa.Column('risk_result_json', sa.JSON(), nullable=True),
    sa.Column('final_decision', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['input_snapshot_id'], ['data_snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    with op.batch_alter_table('decision_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_logs_decision_type'), ['decision_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_logs_input_snapshot_id'), ['input_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_logs_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_decision_logs_type_symbol', ['decision_type', 'symbol'], unique=False)

    op.create_table('holding_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('avg_buy_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('return_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('technical_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('news_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('earnings_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ai_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('grade', sa.String(length=8), nullable=True),
    sa.Column('decision', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('alert', sa.Boolean(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['data_snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_date', 'check_type', 'symbol', name='uq_holding_checks_date_type_symbol')
    )
    with op.batch_alter_table('holding_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_checks_check_date'), ['check_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_checks_check_type'), ['check_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_checks_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_checks_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_holding_checks_symbol_date', ['symbol', 'check_date'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('message_type', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('related_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_job_id'], ['job_runs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_channel'), ['channel'], unique=False)
        batch_op.create_index('ix_notification_logs_channel_status', ['channel', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_related_job_id'), ['related_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_status'), ['status'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('technical_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('news_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('supply_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fundamental_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ai_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('risk_note', sa.Text(), nullable=True),
    sa.Column('watch_condition', sa.Text(), nullable=True),
    sa.Column('invalid_condition', sa.Text(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.run_id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['data_snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'rank', name='uq_recommendations_run_rank'),
    sa.UniqueConstraint('run_id', 'symbol', name='uq_recommendations_run_symbol')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_recommendations_run_symbol', ['run_id', 'symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_symbol'), ['symbol'], unique=False)

    op.create_table('report_score_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('report_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('theme_signal_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('theme_count', sa.Integer(), nullable=True),
    sa.Column('signal_event_count', sa.Integer(), nullable=True),
    sa.Column('target_upside_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rating_score_avg', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('recency_bonus', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('theme_signal_bonus', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('event_signal_bonus', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('risk_penalty', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('recommendation_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'score_date', 'recommendation_run_id', name='uq_report_score_logs_symbol_date_run')
    )
    with op.batch_alter_table('report_score_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_score_logs_recommendation_run_id'), ['recommendation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_score_logs_score_date'), ['score_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_score_logs_symbol'), ['symbol'], unique=False)

    op.create_table('report_themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_name', sa.String(length=128), nullable=False),
    sa.Column('theme_category', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('time_horizon', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('source_report_id', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_report_id'], ['analyst_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_report_id', 'theme_name', name='uq_report_themes_report_theme')
    )
    with op.batch_alter_table('report_themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_themes_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_themes_source_report_id'), ['source_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_themes_theme_category'), ['theme_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_themes_theme_name'), ['theme_name'], unique=False)

    op.create_table('stock_universe_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('universe_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['universe_id'], ['stock_universes.universe_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('universe_id', 'symbol', name='uq_stock_universe_members_universe_symbol')
    )
    with op.batch_alter_table('stock_universe_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_universe_members_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_stock_universe_members_symbol_universe', ['symbol', 'universe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_universe_members_universe_id'), ['universe_id'], unique=False)

    op.create_table('recommendation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('result_date', sa.Date(), nullable=False),
    sa.Column('days_after', sa.Integer(), nullable=False),
    sa.Column('open_return', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high_return', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low_return', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close_return', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_return', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('result_status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', 'days_after', name='uq_recommendation_results_recommendation_days')
    )
    with op.batch_alter_table('recommendation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_results_recommendation_id'), ['recommendation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_results_result_date'), ['result_date'], unique=False)

    op.create_table('report_signal_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('strength', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('time_horizon', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['analyst_reports.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['report_themes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'event_type', 'symbol', 'theme_id', name='uq_report_signal_events_report_event_symbol_theme')
    )
    with op.batch_alter_table('report_signal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_signal_events_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_signal_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_signal_events_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_signal_events_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_signal_events_theme_id'), ['theme_id'], unique=False)

    op.create_table('theme_stock_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('relation_type', sa.String(length=32), nullable=True),
    sa.Column('impact_direction', sa.String(length=16), nullable=False),
    sa.Column('impact_strength', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('impact_path', sa.String(length=32), nullable=True),
    sa.Column('benefit_type', sa.String(length=32), nullable=True),
    sa.Column('time_lag', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('source_sentence_summary', sa.String(length=500), nullable=True),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['report_themes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_id', 'symbol', name='uq_theme_stock_mappings_theme_symbol')
    )
    with op.batch_alter_table('theme_stock_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theme_stock_mappings_impact_direction'), ['impact_direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_theme_stock_mappings_impact_path'), ['impact_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_theme_stock_mappings_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_theme_stock_mappings_theme_id'), ['theme_id'], unique=False)

    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_result_id', sa.Integer(), nullable=True),
    sa.Column('signal_action', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=8), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('return_1d', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('return_3d', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('return_5d', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('return_20d', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('result_status', sa.String(length=32), nullable=True),
    sa.Column('cost_adjusted_return_5d', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('regime', sa.String(length=32), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['recommendation_result_id'], ['recommendation_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_run_id', 'recommendation_id', name='uq_backtest_results_run_recommendation')
    )
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_results_backtest_run_id'), ['backtest_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_results_regime'), ['regime'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_results_signal_action'), ['signal_action'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_results_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_results_symbol'))
        batch_op.drop_index(batch_op.f('ix_backtest_results_signal_action'))
        batch_op.drop_index(batch_op.f('ix_backtest_results_regime'))
        batch_op.drop_index(batch_op.f('ix_backtest_results_backtest_run_id'))

    op.drop_table('backtest_results')
    with op.batch_alter_table('theme_stock_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theme_stock_mappings_theme_id'))
        batch_op.drop_index(batch_op.f('ix_theme_stock_mappings_symbol'))
        batch_op.drop_index(batch_op.f('ix_theme_stock_mappings_impact_path'))
        batch_op.drop_index(batch_op.f('ix_theme_stock_mappings_impact_direction'))

    op.drop_table('theme_stock_mappings')
    with op.batch_alter_table('report_signal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_signal_events_theme_id'))
        batch_op.drop_index(batch_op.f('ix_report_signal_events_symbol'))
        batch_op.drop_index(batch_op.f('ix_report_signal_events_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_signal_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_report_signal_events_direction'))

    op.drop_table('report_signal_events')
    with op.batch_alter_table('recommendation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_results_result_date'))
        batch_op.drop_index(batch_op.f('ix_recommendation_results_recommendation_id'))

    op.drop_table('recommendation_results')
    with op.batch_alter_table('stock_universe_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_universe_members_universe_id'))
        batch_op.drop_index('ix_stock_universe_members_symbol_universe')
        batch_op.drop_index(batch_op.f('ix_stock_universe_members_symbol'))

    op.drop_table('stock_universe_members')
    with op.batch_alter_table('report_themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_themes_theme_name'))
        batch_op.drop_index(batch_op.f('ix_report_themes_theme_category'))
        batch_op.drop_index(batch_op.f('ix_report_themes_source_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_themes_direction'))

    op.drop_table('report_themes')
    with op.batch_alter_table('report_score_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_score_logs_symbol'))
        batch_op.drop_index(batch_op.f('ix_report_score_logs_score_date'))
        batch_op.drop_index(batch_op.f('ix_report_score_logs_recommendation_run_id'))

    op.drop_table('report_score_logs')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_symbol'))
        batch_op.drop_index(batch_op.f('ix_recommendations_snapshot_id'))
        batch_op.drop_index('ix_recommendations_run_symbol')
        batch_op.drop_index(batch_op.f('ix_recommendations_run_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_market'))

    op.drop_table('recommendations')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_status'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_related_job_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_message_type'))
        batch_op.drop_index('ix_notification_logs_channel_status')
        batch_op.drop_index(batch_op.f('ix_notification_logs_channel'))

    op.drop_table('notification_logs')
    with op.batch_alter_table('holding_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_holding_checks_symbol_date')
        batch_op.drop_index(batch_op.f('ix_holding_checks_symbol'))
        batch_op.drop_index(batch_op.f('ix_holding_checks_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_holding_checks_check_type'))
        batch_op.drop_index(batch_op.f('ix_holding_checks_check_date'))

    op.drop_table('holding_checks')
    with op.batch_alter_table('decision_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_decision_logs_type_symbol')
        batch_op.drop_index(batch_op.f('ix_decision_logs_symbol'))
        batch_op.drop_index(batch_op.f('ix_decision_logs_input_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_decision_logs_decision_type'))

    op.drop_table('decision_logs')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_symbol'))
        batch_op.drop_index(batch_op.f('ix_stocks_market'))

    op.drop_table('stocks')
    with op.batch_alter_table('stock_universes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_universes_name'))

    op.drop_table('stock_universes')
    with op.batch_alter_table('stock_indicators', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_indicators_symbol_date')
        batch_op.drop_index(batch_op.f('ix_stock_indicators_symbol'))
        batch_op.drop_index(batch_op.f('ix_stock_indicators_date'))

    op.drop_table('stock_indicators')
    with op.batch_alter_table('report_consensus_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_consensus_snapshots_symbol'))
        batch_op.drop_index(batch_op.f('ix_report_consensus_snapshots_snapshot_date'))

    op.drop_table('report_consensus_snapshots')
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_runs_status'))
        batch_op.drop_index(batch_op.f('ix_recommendation_runs_run_date'))
        batch_op.drop_index('ix_recommendation_runs_date_status')

    op.drop_table('recommendation_runs')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_theme'))
        batch_op.drop_index(batch_op.f('ix_news_items_source'))
        batch_op.drop_index('ix_news_items_published_source')
        batch_op.drop_index(batch_op.f('ix_news_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_items_category'))

    op.drop_table('news_items')
    with op.batch_alter_table('market_regimes', schema=None) as batch_op:
        batch_op.drop_index('ix_market_regimes_market_date')
        batch_op.drop_index(batch_op.f('ix_market_regimes_market'))
        batch_op.drop_index(batch_op.f('ix_market_regimes_date'))

    op.drop_table('market_regimes')
    with op.batch_alter_table('market_cap_rankings', schema=None) as batch_op:
        batch_op.drop_index('ix_market_cap_rankings_symbol_date')
        batch_op.drop_index(batch_op.f('ix_market_cap_rankings_symbol'))
        batch_op.drop_index(batch_op.f('ix_market_cap_rankings_rank_date'))
        batch_op.drop_index(batch_op.f('ix_market_cap_rankings_market'))
        batch_op.drop_index('ix_market_cap_rankings_date_market')

    op.drop_table('market_cap_rankings')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_status'))
        batch_op.drop_index('ix_job_runs_name_status')
        batch_op.drop_index(batch_op.f('ix_job_runs_job_name'))

    op.drop_table('job_runs')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index('ix_holdings_symbol_active')
        batch_op.drop_index(batch_op.f('ix_holdings_symbol'))

    op.drop_table('holdings')
    with op.batch_alter_table('fundamental_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fundamental_snapshots_symbol'))
        batch_op.drop_index(batch_op.f('ix_fundamental_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_fundamental_snapshots_fiscal_year'))

    op.drop_table('fundamental_snapshots')
    with op.batch_alter_table('earnings_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_earnings_events_symbol'))
        batch_op.drop_index(batch_op.f('ix_earnings_events_surprise_type'))
        batch_op.drop_index(batch_op.f('ix_earnings_events_event_date'))

    op.drop_table('earnings_events')
    with op.batch_alter_table('data_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_data_snapshots_symbol_type_time')
        batch_op.drop_index(batch_op.f('ix_data_snapshots_symbol'))
        batch_op.drop_index(batch_op.f('ix_data_snapshots_snapshot_type'))
        batch_op.drop_index(batch_op.f('ix_data_snapshots_snapshot_time'))

    op.drop_table('data_snapshots')
    with op.batch_alter_table('daily_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_prices_symbol_date')
        batch_op.drop_index(batch_op.f('ix_daily_prices_symbol'))
        batch_op.drop_index(batch_op.f('ix_daily_prices_date'))

    op.drop_table('daily_prices')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_strategy_name'))
        batch_op.drop_index(batch_op.f('ix_backtest_runs_run_date'))

    op.drop_table('backtest_runs')
    with op.batch_alter_table('analyst_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_reports_symbol'))
        batch_op.drop_index(batch_op.f('ix_analyst_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_analyst_reports_published_at'))
        batch_op.drop_index(batch_op.f('ix_analyst_reports_duplicate_group_key'))

    op.drop_table('analyst_reports')
    # ### end Alembic commands ###
