"""auth foundation -- v0.8 Phase B (28th + 29th tables)

Revision ID: 0002_auth_foundation
Revises: 0001_baseline_v0_7
Create Date: 2026-05-06

Adds two new tables on top of the v0.7-final baseline:

  * ``users`` (28th) -- single admin account. password_hash uses scrypt
    (app/auth/security.py); plaintext passwords are NEVER stored.
    multi-user / RBAC / OAuth / SSO are out of scope for v0.8 (see PLAN-0008).
  * ``login_audit_logs`` (29th) -- append-only LOGIN_SUCCESS / LOGIN_FAILED /
    LOGOUT events. source_ip / user_agent are SHA256-hashed before insert
    (`app.auth.security.hash_for_audit`); raw values are NEVER persisted.

This revision touches no other tables and adds no FK back-references that
would mutate existing rows. Operational rollout: see INTEGRATION_RUNBOOK
section 17 -- backup, then `alembic upgrade head`.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_auth_foundation'
down_revision: Union[str, Sequence[str], None] = '0001_baseline_v0_7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('login_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('source_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_login_audit_logs_event_created', ['event_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_audit_logs_username'), ['username'], unique=False)
        batch_op.create_index('ix_login_audit_logs_username_created', ['username', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_login_audit_logs_username_created')
        batch_op.drop_index(batch_op.f('ix_login_audit_logs_username'))
        batch_op.drop_index(batch_op.f('ix_login_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_audit_logs_event_type'))
        batch_op.drop_index('ix_login_audit_logs_event_created')
        batch_op.drop_index(batch_op.f('ix_login_audit_logs_created_at'))

    op.drop_table('login_audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
