"""watchlist -- v0.8 Phase C (30th + 31st tables)

Revision ID: 0003_watchlist
Revises: 0002_auth_foundation
Create Date: 2026-05-06

Adds two new tables on top of the v0.8 Phase B auth foundation:

  * ``watchlists`` (30th) -- a named bucket of stocks owned by exactly one
    User. Unique(user_id, name) prevents collisions per owner. Repositories
    enforce the "at most one is_default per user" invariant.
  * ``watchlist_items`` (31st) -- a single symbol inside a watchlist plus an
    optional <=500-char operator memo. Unique(watchlist_id, symbol) prevents
    duplicates. ON DELETE CASCADE removes items when their watchlist is
    deleted.

This revision adds NO broker / account / quantity / order_price / order_type /
side columns. WatchlistItem is a "favourite", not an order. Operational
rollout: see INTEGRATION_RUNBOOK section 17 -- backup, then `alembic upgrade
head`.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_watchlist'
down_revision: Union[str, Sequence[str], None] = '0002_auth_foundation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlists_user_name')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_user_id'), ['user_id'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'symbol', name='uq_watchlist_items_watchlist_symbol')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_items_watchlist_id'), ['watchlist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_watchlist_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_items_symbol'))

    op.drop_table('watchlist_items')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_user_id'))

    op.drop_table('watchlists')
    # ### end Alembic commands ###
