"""Scheduler package. Jobs are introduced after core services exist."""

from app.scheduler.jobs import (
    JOB_FUNCTIONS,
    JOB_NAME_CALCULATE_INDICATORS,
    JOB_NAME_COLLECT_MARKET_CLOSE,
    JOB_NAME_POST_MARKET_HOLDING_CHECK,
    JOB_NAME_PRE_MARKET_HOLDING_CHECK,
    JOB_NAME_SEND_RECOMMENDATION_REPORT,
    JOB_NAME_UPDATE_RECOMMENDATION_RESULTS,
    JOB_STATUS_FAILED,
    JOB_STATUS_PARTIAL,
    JOB_STATUS_RUNNING,
    JOB_STATUS_SUCCESS,
    JobOutcome,
    JobResult,
    calculate_technical_indicators,
    collect_market_close_data,
    run_job,
    run_post_market_holding_check,
    run_pre_market_holding_check,
    send_recommendation_report,
    update_recommendation_results,
)

__all__ = [
    "JOB_FUNCTIONS",
    "JOB_NAME_CALCULATE_INDICATORS",
    "JOB_NAME_COLLECT_MARKET_CLOSE",
    "JOB_NAME_POST_MARKET_HOLDING_CHECK",
    "JOB_NAME_PRE_MARKET_HOLDING_CHECK",
    "JOB_NAME_SEND_RECOMMENDATION_REPORT",
    "JOB_NAME_UPDATE_RECOMMENDATION_RESULTS",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_PARTIAL",
    "JOB_STATUS_RUNNING",
    "JOB_STATUS_SUCCESS",
    "JobOutcome",
    "JobResult",
    "calculate_technical_indicators",
    "collect_market_close_data",
    "run_job",
    "run_post_market_holding_check",
    "run_pre_market_holding_check",
    "send_recommendation_report",
    "update_recommendation_results",
]
